=== luCmoi/SandArena/android/assets/XML/carte.dtd
<!ELEMENT listecarte (entrecarte*)>
    <!ELEMENT entrecarte (typestatic,
        emplacement)>

        <!ATTLIST entrecarte
            id NMTOKEN #REQUIRED
            type NMTOKEN #REQUIRED
            taillex NMTOKEN #REQUIRED
            tailley NMTOKEN #REQUIRED
            nbperso NMTOKEN #REQUIRED>

        <!ELEMENT typestatic (casestatic*)>

            <!ELEMENT casestatic  EMPTY>
                <!ATTLIST casestatic
                    type NMTOKEN  #REQUIRED
                    x NMTOKEN  #REQUIRED
                    y NMTOKEN  #REQUIRED>

        <!ELEMENT emplacement (caseemplacement+)>
            <!ELEMENT caseemplacement EMPTY>
                <!ATTLIST caseemplacement
                    joueur NMTOKEN  #REQUIRED
                    x NMTOKEN  #REQUIRED
                    y NMTOKEN  #REQUIRED>

=== luCmoi/SandArena/android/assets/XML/carte.xml
<?xml version="1.0" encoding="ISO-8859-1"?><!DOCTYPE listecarte SYSTEM "XML/carte.dtd">
<listecarte>
    <entrecarte id ="3001" type="sable" taillex="10" tailley="8" nbperso="4">
        <typestatic></typestatic>
        <emplacement>
            <caseemplacement joueur="0" x="0" y="0" />
            <caseemplacement joueur="0" x="0" y="1"/>
            <caseemplacement joueur="0" x="0" y="2"/>
            <caseemplacement joueur="0" x="0" y="3"/>
            <caseemplacement joueur="1" x="5" y="0"/>
            <caseemplacement joueur="1" x="5" y="1"/>
            <caseemplacement joueur="1" x="5" y="2"/>
            <caseemplacement joueur="1" x="5" y="3"/>
        </emplacement>
    </entrecarte>
</listecarte>
