=== luCmoi/SandArena/android/assets/XML/competence.dtd
<!ELEMENT listecompetence (entrecomp*)>
	<!ELEMENT entrecomp (nom, description, image, 
		(compattaque | compdeclencheureffet | compbuff | compbuffactif | compdispel),
		affinite) >
		<!ELEMENT nom (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT image (#PCDATA)>
		
		<!ELEMENT complance EMPTY>
		<!ATTLIST complance
			recharge NMTOKEN  #REQUIRED
			utilisation NMTOKEN  #REQUIRED
			porte NMTOKEN  #REQUIRED
			portemin NMTOKEN  #REQUIRED
			zone NMTOKEN  #REQUIRED
			caract NMTOKEN  #REQUIRED
		>
		
		<!ELEMENT compattaque (complance, compbuff?)>
		<!ATTLIST compattaque
			bonus NMTOKEN  #REQUIRED
		>
		
		<!ELEMENT compdeclencheureffet (compbuff | compattaque)>
		<!ATTLIST compdeclencheureffet
			typedeclencheur NMTOKEN  #REQUIRED
			cible NMTOKEN  #REQUIRED
		>
		
		<!ELEMENT compbuffactif (complance, compbuff)>

		
		<!ELEMENT compdispel (complance, compbuff?)>
		<!ATTLIST compdispel
			cible NMTOKEN  #REQUIRED
			nombre NMTOKEN  #REQUIRED
		>
		
		<!ELEMENT compbuff ((condtype | condduree)*, compbuff?)>
		<!ATTLIST compbuff
			type NMTOKEN  #REQUIRED
			valeur NMTOKEN  #REQUIRED
		>
		
		<!ELEMENT condtype (#PCDATA)>
		<!ELEMENT condduree (#PCDATA)>
		
		<!ELEMENT affinite (entreaffinite+)>
		<!ELEMENT entreaffinite (#PCDATA)>

		<!ENTITY affforce "0">
		<!ENTITY afftribal "1">
		<!ENTITY affagilite "2">
		<!ENTITY affpoison "3">
		
		<!ENTITY bufftypeattaque "0">
		<!ENTITY bufftypedefense "1">
		<!ENTITY buffdot "4">
		<!ENTITY buffvalvitesse "5">
		<!ENTITY buffvalattaque "6">
		<!ENTITY buffdegat "7">
		<!ENTITY buffstun "8">
		<!ENTITY buffvaldefense "9">
		
		<!ENTITY caractforce "0">
		<!ENTITY caractagilite "1">
		<!ENTITY caractmagie "2">

=== luCmoi/SandArena/android/assets/XML/competence.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE listecompetence SYSTEM "competence.dtd">
<listecompetence>
	
	
	<entrecomp>
		<nom>Bourre-pif</nom>
		<description>Coup de poing puissant au visage, de préférence dans le nez</description>
		<image>Image/Competence/Bourrepif.png</image>
		<compattaque bonus="1">
			<complance recharge="0" utilisation="0" porte="1" portemin="1" zone="1" caract ="&caractforce;"/>
		</compattaque>
		<affinite>
			<entreaffinite>&affforce;</entreaffinite>
		</affinite>
	</entrecomp>
	
	
	<entrecomp>
		<nom>Leg Day</nom>
		<description>Le personnage à travaillé ses jambes tous les jours</description>
		<image>Image/Competence/LegDay.png</image>
		<compbuff type="&buffvalvitesse;" valeur = "4">
		</compbuff>
		<affinite>
			<entreaffinite>&affforce;</entreaffinite>
		</affinite>
	</entrecomp>
		
	
	<entrecomp>
		<nom>Rituel de sang</nom>
		<description>Parfoit il faut sacrifier une partie de soit pour en renforcer une autre</description>
		<image>Image/Competence/RituelDeSang.png</image>
		<compbuffactif>
			<complance recharge="3" utilisation="0" porte="0" portemin="0" zone="1" caract="&caractmagie;"/>
			<compbuff type="&buffdegat;" valeur = "4">
				<compbuff type="&buffvalattaque;" valeur = "1">
				</compbuff>
			</compbuff>
		</compbuffactif>
		<affinite>
			<entreaffinite>&afftribal;</entreaffinite>
		</affinite>
	</entrecomp>
	
	
	<entrecomp>
		<nom>Perle de Purification</nom>
		<description>Purifie le corps de ses afflictions</description>
		<image>Image/Competence/PerleDePurification.png</image>
		<compdispel cible="0" nombre="1">
			<complance recharge="4" utilisation="3" porte="4" portemin="0" zone="1" caract="&caractmagie;"/>
		</compdispel>
		<affinite>
			<entreaffinite>&afftribal;</entreaffinite>
		</affinite>
	</entrecomp>
	
	
</listecompetence>
